area-mapping:
    shanghai: 
        dataCenterId: 0
        dataSourceName: adminDataSource
    guangdong:
        dataCenterId: 1
        dataSourceName: zwjkDataSource
    zhejiang:
        dataCenterId: 2
        dataSourceName: zwjk2DataSource
